import Link from "next/link";
import { redirect } from "next/navigation";
import { getCurrentProfile } from "@/lib/auth";
import { getStorefrontData } from "@/lib/storefront";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { verifyInventoryAction, updateWithdrawalAction } from "./actions";
export const metadata = { title: "Operación y reclamos", robots: { index: false, follow: false } };
export default async function Operations() {
  if ((await getCurrentProfile()).profile?.role !== "admin") redirect("/login?next=/admin/operaciones");
  const db = await createServerSupabaseClient();
  const [{ products }, requests, reviews] = await Promise.all([getStorefrontData({ admin: true }), db.from("withdrawal_requests").select("reference,order_code,email,reason,created_at,status").order("created_at", { ascending: false }).limit(100), db.from("orders").select("tracking_code,total_amount,status,customer_email,payment_id").eq("payment_review", true).limit(100)]);
  return <div className="mx-auto max-w-5xl space-y-8 p-5"><Link href="/admin" className="underline">Volver al panel</Link><h1 className="text-3xl font-bold">Operación y reclamos</h1>
    <section><h2 className="text-xl font-bold">Arrepentimientos recibidos</h2>{requests.error ? <p>Registro pendiente de migración.</p> : requests.data?.length ? requests.data.map(r => <form action={updateWithdrawalAction} className="my-3 space-y-2 rounded-lg border p-3" key={r.reference}><p>{r.reference} · {r.order_code} · {r.email} · {new Date(r.created_at).toLocaleDateString("es-AR")}</p><p>{r.reason || "Sin motivo indicado."}</p><input type="hidden" name="reference" value={r.reference} /><label className="mr-3">Estado <select name="status" defaultValue={r.status} className="rounded border p-2"><option value="received">Recibida</option><option value="contacted">Contactada</option><option value="resolved">Resuelta</option></select></label><button className="rounded bg-zinc-950 px-4 py-2 text-white">Guardar estado</button></form>) : <p>Sin solicitudes.</p>}</section>
    <section><h2 className="text-xl font-bold">Pagos que requieren revisión</h2><p>Conciliar cobros tardíos, duplicados, devoluciones y contracargos antes de despachar.</p>{reviews.error ? <p>Registro pendiente de migración.</p> : reviews.data?.map(r => <p className="my-3 rounded-lg border p-3" key={r.tracking_code}>{r.tracking_code} · {r.customer_email} · ${r.total_amount} · {r.status} · Pago {r.payment_id}</p>)}</section>
    <form action={verifyInventoryAction} className="space-y-4 rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">Verificar inventario y ficha</h2><p>No verifica productos con reservas pendientes. Primero resolvé esos pedidos. Contá unidades disponibles, descontando las ya vendidas.</p><select aria-label="Producto" required name="product_id" className="w-full rounded-lg border p-3"><option value="">Elegí el producto</option>{products.map(p => <option key={p.id} value={p.id}>{p.title}</option>)}</select><label className="block">Unidades disponibles<input required name="stock" type="number" min="0" step="1" className="ml-3 rounded-lg border p-2" /></label><label className="block">Peso por unidad (kg; cero si desconocido)<input required name="weight" type="number" min="0" step="0.001" className="ml-3 rounded-lg border p-2" /></label><div className="grid gap-3 md:grid-cols-2">{["modelo","contenido","ingredientes","uso","precauciones","incluye","compatibilidad","responsable_local","lote","vencimiento","warranty"].map(k => <label key={k} className="block">{k === "warranty" ? "Condiciones documentadas de garantía" : k.replaceAll("_", " ")}<textarea name={k} maxLength={3000} className="mt-1 w-full rounded-lg border p-2" /></label>)}</div><label className="flex gap-2"><input required name="confirmed" type="checkbox" />Verifiqué stock físico y la información cargada.</label><button className="rounded-xl bg-zinc-950 p-3 text-white">Guardar verificación</button></form>
  </div>;
}
