import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import nextEnv from '@next/env';
import { createClient } from '@supabase/supabase-js';
import sharp from 'sharp';
nextEnv.loadEnvConfig(process.cwd());
const db=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{persistSession:false}});
const source='https://totaltools.com.tw/image/cache/catalog/THT108313-550x550w.png.webp';
const response=await fetch(source,{signal:AbortSignal.timeout(30000)});
assert.equal(response.status,200);
const data=Buffer.from(await response.arrayBuffer());
const photo=sharp(data);const metadata=await photo.metadata();await photo.raw().toBuffer();
assert.equal(metadata.format,'webp');assert.ok((metadata.width||0)>=500&&(metadata.height||0)>=500);
const path='catalog-2026-10-06-total-tht108313.webp';
const {error:uploadError}=await db.storage.from('product-images').upload(path,data,{contentType:'image/webp',upsert:false});
if(uploadError)throw uploadError;
const {data:publicData}=db.storage.from('product-images').getPublicUrl(path);
const {data:updated,error}=await db.from('products').update({image_url:publicData.publicUrl,image_urls:[publicData.publicUrl],updated_at:new Date().toISOString()}).eq('id','14b00e75-d5f8-509f-93cf-9fda71c5d1d9').eq('image_url',source).select('id,image_url');
if(error)throw error;assert.equal(updated?.length,1);
const report={source,publicUrl:publicData.publicUrl,width:metadata.width,height:metadata.height,format:metadata.format,bytes:data.length,checkedAt:new Date().toISOString(),unchangedImageBytes:true};
await fs.writeFile('docs/tools-jack3-2026-10-06/media-published.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
