import fs from 'node:fs/promises';
import nextEnv from '@next/env';
import { createClient } from '@supabase/supabase-js';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import sharp from 'sharp';
nextEnv.loadEnvConfig(process.cwd());
const db=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{persistSession:false}});
const dir='docs/mango-fuerza-2026-10-08',stamp=new Date().toISOString();
const payload=JSON.parse(await fs.readFile(`${dir}/payload.json`,'utf8'));
const existing=await db.from('products').select('id').or('model.eq.THPTW1425N8,sku.eq.598408');if(existing.error)throw existing.error;assert.equal(existing.data.length,0);
const bytes=await fs.readFile(`${dir}/torquimetro.jpg`);await sharp(bytes).raw().toBuffer();
const path='catalog-2026-10-08-total-thptw1425n8.jpg';
const upload=await db.storage.from('product-images').upload(path,bytes,{contentType:'image/jpeg',upsert:false});if(upload.error)throw upload.error;
const image=db.storage.from('product-images').getPublicUrl(path).data.publicUrl;
const supplier='https://www.totalherramientasoficial.com.py/produto/total-llave-dinamometrica-preajustable-525nm---thptw1425n8-57169.html';
const ml='https://articulo.mercadolibre.com.ar/MLA-2155355561-torquimetro-14-5-25nm-3-l280mm-estuche-industrial-_JM';
const purchase=Math.round(136.49*328.43*100)/100;
const product={...payload.product,id:randomUUID(),title:'Total Torquímetro preajustable 1/4 pulgada 5–25 Nm con estuche THPTW1425N8',slug:'total-torquimetro-1-4-5-25-nm-estuche-thptw1425n8',model:'THPTW1425N8',sku:'598408',retail_price:89900,is_active:false,image_url:image,image_urls:[image],source_url:supplier,supplier_live_price:purchase,supplier_last_checked_at:stamp,tags:['Total','Herramientas','Torquímetro','Llave dinamométrica','Taller','Torque'],description:'Torquímetro manual preajustable Total con encastre de 1/4 pulgada y rango de ajuste de 5 a 25 Nm. Permite aplicar el par indicado para tornillos y tuercas compatibles, en tareas de montaje y mantenimiento. Tiene 280 mm de largo y una tolerancia de par declarada de ±3%.\nIncluye estuche plástico para transporte y guardado. Seleccioná el torque indicado por el fabricante de la pieza y verificá que esté dentro del rango de esta herramienta.\nConsultá disponibilidad y condiciones de entrega antes de comprar.',specifications:{Gama:'Industrial',Tipo:'Manual preajustable',Encastre:'1/4 pulgada','Rango de torque':'5–25 Nm',Longitud:'280 mm','Tolerancia de par':'±3%',Incluye:'Torquímetro y estuche plástico'}};
const cost={...payload.cost,product_id:product.id,origin_cost:purchase,supplier_url:supplier,verified_at:stamp,ml_price:99900,ml_url:ml,ml_checked_at:stamp,source_document:`Alta solicitada por el dueño el08/10/2026. Proveedor navegador ficha principal THPTW1425N8 SKU598408 disponible. Precio CON IVA USD26,40 / BRL136,49. Costo BRL136,49 × ARS328,43 por real (misma cotización indicada para esta operación) = ARS${purchase}. Guardado convertido en ARS, exchange_rate1 porque esquema no admite BRL. Referencia ML exacta verificada en navegador, modelo THPTW1425N8, Total, encastre1/4, rango5-25Nm,280mm, estuche, vendedor AJC MOTOS-RODAMIENTOS OK, última unidad, ARS99900 con impuestos. Venta ARS89900, ML×0,90 redondeo hacia abajo a ARS100. Diferencia antes de gastos ARS${(89900-purchase).toFixed(2)}, no ganancia neta. Flete, internación y comisiones pendientes; ceros requeridos no son gastos gratuitos; expenses_confirmed=false. Stock físico propio0. Costos y fuentes privados.`};
await fs.writeFile(`${dir}/torquimetro-payload.json`,JSON.stringify({product:{...product,is_active:true},cost},null,2));
const p=await db.from('products').insert(product);if(p.error)throw p.error;
const c=await db.from('product_costs').insert(cost);if(c.error)throw c.error;
const a=await db.from('products').update({is_active:true,updated_at:stamp}).eq('id',product.id).eq('is_active',false).select('id');if(a.error)throw a.error;assert.equal(a.data.length,1);
console.log(JSON.stringify({published:true,price:89900,purchase,url:`https://myaimportaciones.vercel.app/producto/${product.slug}`}));
